### ISSUE TITLE
If a player has 5+ wins in a row, he should be retired for 2 weeks. 

### ISSUE THREAD

**Issue by sjangra-git** [michaeljacobdavis/foos-bot#13]
Also, if they come back again and again 5+ wins in a row, the retirement period increases to 3, 5, 8, 12 ...

**Comment by clogston** [comment]
This'll just make it really hard to unseat someone. They have to be eligible to lose games if you want them to move down.

**Comment by michaeljacobdavis** [comment]
Ya, I feel like the real way to solve this is ranking, so closing for now in favor of #15.
