### ISSUE TITLE
Post periodic reminder when game waiting for additional players

### ISSUE THREAD

**Issue by clogston** [michaeljacobdavis/foos-bot#6]
For your consideration,
Bot posts current player list at game start and when players join. Could also post at a fixed interval that a game is waiting for players. 3 minutes? 5 minutes?

**Comment by michaeljacobdavis** [comment]
Makes sense if there is a lot of activity, but thing I'd be weary of is whether or not someone who was in, after 20 mins, is now unavailable.

One thing that is tangential to this that I was thinking of is auto stopping games after X mins.

Any other thoughts on either of these?

**Comment by clogston** [comment]
Auto-stop is a better idea. Side effect of initial idea was that people who were `!in` would be reminded of their status. Auto-stop solves it.

**Comment by michaeljacobdavis** [comment]
Nice! Will do that.
